### ISSUE TITLE
Tomcat 8.5.x support for Hazelcast tomcat session manager

### ISSUE THREAD

**Issue by Anya1001** [hazelcast/hazelcast-tomcat-sessionmanager#16]
Can't start Tomcat 8.5.11 or 8.5.4 with P2P Hazelcast tomcat session manager. Works on Tomcat 8.0.41.
Tomcat fails to start with errors:
25-Jan-2017 16:43:24.664 SEVERE [localhost-startStop-1] org.apache.tomcat.util.digester.Digester.startElement Begin event threw erro
r
 java.lang.NoClassDefFoundError: org/apache/catalina/util/LifecycleSupport
        at com.hazelcast.session.HazelcastSessionManager.<init>(HazelcastSessionManager.java:36)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:117)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1190)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.ja
va:1338)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScan
nerImpl.java:2781)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:5
04)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1458)
        at org.apache.catalina.startup.ContextConfig.processContextConfig(ContextConfig.java:537)
        at org.apache.catalina.startup.ContextConfig.contextConfig(ContextConfig.java:475)
        at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:738)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:310)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:395)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:108)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.catalina.util.LifecycleSupport
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 34 more

25-Jan-2017 16:43:24.667 SEVERE [localhost-startStop-1] org.apache.tomcat.util.digester.Digester.startElement Begin event threw erro
r
 java.lang.NoClassDefFoundError: org/apache/catalina/util/LifecycleSupport
        at com.hazelcast.session.HazelcastSessionManager.<init>(HazelcastSessionManager.java:36)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:117)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1190)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.ja
va:1338)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScan
nerImpl.java:2781)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:5
04)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1458)
        at org.apache.catalina.startup.ContextConfig.processContextConfig(ContextConfig.java:537)
        at org.apache.catalina.startup.ContextConfig.contextConfig(ContextConfig.java:475)
        at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:738)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:310)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:395)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:108)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mesutcelik** [comment]
Unfortunately, Tomcat 8.5 is not supported yet. 
We would want to spend time on it in future but any contribution would be pretty much appreciated!

Thanks for heads up!

**Comment by st0ne-dot-at** [comment]
just added a pull request: https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/pull/17

**Comment by wellprado** [comment]
Hi guys,

 Some news about when this problem will be fixed ?

06-Mar-2017 23:58:56.986 SEVERE [alien1-startStop-1] org.apache.tomcat.util.digester.Digester.startElement Begin event threw error
 java.lang.NoClassDefFoundError: org/apache/catalina/util/LifecycleSupport
        at com.hazelcast.session.HazelcastSessionManager.<init>(HazelcastSessionManager.java:36)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:117)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1190)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1458)
        at org.apache.catalina.startup.ContextConfig.processContextConfig(ContextConfig.java:537)
        at org.apache.catalina.startup.ContextConfig.contextConfig(ContextConfig.java:475)
        at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:738)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:310)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:395)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:108)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.catalina.util.LifecycleSupport
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 38 more


My tomcat version is :

[root@alien1 bin]# ./version.sh
Using CATALINA_BASE:   /u01/tomcat
Using CATALINA_HOME:   /u01/tomcat
Using CATALINA_TMPDIR: /u01/tomcat/temp
Using JRE_HOME:        /usr/lib/jvm/jre
Using CLASSPATH:       /u01/tomcat/bin/bootstrap.jar:/u01/tomcat/bin/tomcat-juli.jar
Server version: Apache Tomcat/8.5.11
Server built:   Jan 10 2017 21:02:52 UTC
Server number:  8.5.11.0
OS Name:        Linux
OS Version:     4.1.12-61.1.25.el7uek.x86_64
Architecture:   amd64
JVM Version:    1.8.0_121-b13
JVM Vendor:     Oracle Corporation


Regards

**Comment by emre-aydin** [comment]
Hi @wellprado 
@st0ne-dot-at's PR has been merged, we will release the new version with Tomcat 8.5 support in a few days. I will update you when we release.

**Comment by wellprado** [comment]
Hi @emre-aydin,

  It's a great news. I can't wait for that.
  Thank you very much for your dedication in this project fellas.

Any date hunch?

Regards

**Comment by emre-aydin** [comment]
Hi @wellprado 

We plan to release it today.

**Comment by emre-aydin** [comment]
@wellprado @st0ne-dot-at @Anya1001 
Version 1.1 is released. It has support for Tomcat 8.5.

**Comment by wellprado** [comment]
Hi Emre,


 Thank you very much.


Where can I download this fix ?


Thank you

________________________________
De: Emre Aydın <notifications@github.com>
Enviado: quinta-feira, 9 de março de 2017 19:08:12
Para: hazelcast/hazelcast-tomcat-sessionmanager
Cc: Wellington Prado; Mention
Assunto: Re: [hazelcast/hazelcast-tomcat-sessionmanager] Tomcat 8.5.x support for Hazelcast tomcat session manager (#16)


@wellprado<https://github.com/wellprado> @st0ne-dot-at<https://github.com/st0ne-dot-at> @Anya1001<https://github.com/Anya1001>
Version 1.1 is released. It has support for Tomcat 8.5.

**Comment by emre-aydin** [comment]
You can download it from here:
https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/releases/tag/v1.1

On Fri, Mar 10, 2017 at 12:08 AM, Wellington Prado <notifications@github.com
